#!/bin/sh

if [ `uname` == Darwin ] ; then
  export DYLD_LIBRARY_PATH=`brew --prefix openssl`/lib:$DYLD_LIBRARY_PATH
fi

# if being executed from installation into some base directory,
# we make sure we are running standing at this location
if expr "$0" : '.*\/bin\/openbazaar$' > /dev/null ; then
  BASE=${0%/bin/openbazaar}/share/openbazaar
  (cd $BASE && /usr/bin/env python -m node.openbazaar "$@") &
else
  ./env/bin/python -m node.openbazaar "$@" &
  #/usr/bin/env python -m node.openbazaar "$@" &
fi
